---
language: node_js
node_js:
  - 6
  - 8
  - 9
cache:
  yarn: true
  directories:
  - node_modules
  - /home/travis/.pyenv_cache
install:
  - yarn install
before_install:
  - export PYTHON_BUILD_CACHE_PATH="/home/travis/.pyenv_cache"
  - curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
  - export PATH="/home/travis/.pyenv/bin:$PATH"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"
  - pyenv install -s 2.7.11
  - pyenv install -s 3.6.3
  - pyenv global 2.7.11 3.6.3
script:
  - yarn lint
  - yarn test -- --runInBand
