---
language: node_js
node_js:
  - 6
  - 8
  - 9
env:
  - PYTHON_VERSION=2.7.14
  - PYTHON_VERSION=3.6.3
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - pyenv global $PYTHON_VERSION
  - python --version
install:
  - yarn install
script:
  - yarn lint
  - yarn test --runInBand
